### ISSUE TITLE
Api key is missing or invalid

### ISSUE THREAD

**Issue by guile124** [anonanonymous/wallet-api-go#1]
Hi
I'm getting this error, any idea?

![IMG-20190829-WA0030](https://user-images.githubusercontent.com/37140613/63970653-fa0b4280-caa4-11e9-8b4a-f275bb9ab9dc.jpg)

**Comment by anonanonymous** [comment]
This error is most likely due to the `wallet-api` program using a different password than the specified password in `walletapi.InitWalletAPI`.
